

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;

import student.TestCase;

/**
 * This class tests the methods of SkipListProject class
 * which serves as the entry point of the command line
 * program.
 * 
 * @author CS Staff
 * 
 * @version 2024-05-22
 */
public class RectangleDBTest extends TestCase {
    
    private RectangleDB rectDB;
    
    public void setUp()
    {
        // initialize it here
        rectDB = new RectangleDB();
    }
    

    // ----------------------------------------------------------
    /**
     * Read contents of a file into a string
     * 
     * @param path
     *            File name
     * @return the string
     * @throws IOException
     */
    static String readFile(String path) throws IOException {
        byte[] encoded = Files.readAllBytes(Paths.get(path));
        return new String(encoded);
    }

    // TODO: implement test methods


    /**
     * Example 1: Tests the main method when the file name is invalid.
     */
    public void testMainNoArgs() {
        String[] testInput = {};
        RectangleDB.main(testInput);
        assertTrue(fuzzyContains(systemOut().getHistory(), "Invalid file"));
    }


    /**
     * Example 2: Tests the main method when the file name is valid.
     */
    /**
     * This method tests the main functionality of the SkipListProject class.
     * It creates an instance of SkipListProject, calls the toString() method,
     * sets the expected output, sets the test input, and calls the main method
     * of SkipListProject with the test input. Finally, it asserts that the
     * expected output matches the system output.
     * 
     * @throws IOException
     */
    public void testMain() throws IOException {

        // Creates an instance of the RectangleDB
//        RectangleDB rectDB = new RectangleDB();

        // Sets the test input file.
        // This file contains a list of commands to be executed.
        String[] testInput = { "solutionTestData/P1test3.txt" }; // Type is
                                                                    // array of
                                                                    // Strings
                                                                    // to match
                                                                    // the
                                                                    // `main`
                                                                    // argument
        String testOutput = "solutionTestData/P1test3out.txt"; // Type is
                                                                     // String
                                                                     // to match
                                                                     // type of
                                                                     // `readFile`
                                                                     // method

        // TODO Calls the main method of BST with the test input.
        // This should print out all the necessary console output.
        // The main method does NOT print anything console output right now
        // because in its current state it is missing all the necessary methods.
        // Those methods are for you to implement. :)
        
        RectangleDB.main(testInput);

        // TODO Prints dummy console output.
        // You can get rid of the next two statements when are done
        // implementing methods that actual prints to the console output.
//        String dummyConsoleOutput = "Rectangle rejected: (r_r, -1, -20, 3, 4)\n"
//            + "Rectangle rejected: (rec, 7, -8, 1, 3)\n"
//            + "Rectangle rejected: (virtual_rec0, 1, 1, 0, 0)\n"
//            + "Rectangle rejected: (virtual_REC0, 0, 0, 11, 0)\n"
//            + "Rectangle rejected: (inExistRec_0, 1, 1, -1, -2)\n"
//            + "Rectangle rejected: (11, 11, 0, 0)\n" + "Intersection pairs:\n"
//            + "BST dump:\n" + "Node has depth 0, Value (null)\n"
//            + "BST size is: 0\n" + "Rectangle not found: (r_r)\n"
//            + "Rectangle not removed: (r_r)\n"
//            + "Rectangle rejected: (1, 1, 0, 0)\n"
//            + "Rectangles intersecting region (-5, -5, 20, 20):\n" + "";
//        System.out.print(dummyConsoleOutput); // TODO: Comment it out later when
                                              // you actually print to the
                                              // console.

        // TODO Sets the expected output.
        // Change this to the file that contains expected output.
        // Then, you can read the output file and set the expected output from
        // that.
        String expected = readFile(testOutput);

        // asserts that the expected output matches the system output
        // generated by the main method of SkipListProject.
        assertFuzzyEquals(expected, systemOut().getHistory());
        
    }
}
